### ISSUE TITLE
应用主题报错

### ISSUE THREAD

**Issue by yeechongyeung** [GeekaholicLin/hexo-theme-ylion#5]
`
$ hexo g

ERROR Script load failed: themes\hexo-theme-ylion\scripts\generator\index.js
TypeError: Cannot set property 'cdata' of undefined
    at Object.<anonymous> (F:\Githexo\themes\hexo-theme-ylion\scripts\generator\lib\generator.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (F:\Githexo\node_modules\hexo\lib\hexo\index.js:216:21)
    at F:\Githexo\themes\hexo-theme-ylion\scripts\generator\index.js:19:42
    at F:\Githexo\node_modules\hexo\lib\hexo\index.js:232:12
    at tryCatcher (F:\Githexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Githexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\Githexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\Githexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\Githexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\Githexo\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\Githexo\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\Githexo\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\Githexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\Githexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\Githexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\Githexo\node_modules\bluebird\js\release\promise.js:638:18)
    at F:\Githexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at F:\Githexo\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
ERROR Script load failed: themes\hexo-theme-ylion\scripts\generator\lib\generator.js
TypeError: Cannot set property 'cdata' of undefined
    at F:\Githexo\themes\hexo-theme-ylion\scripts\generator\lib\generator.js:5:19
    at F:\Githexo\node_modules\hexo\lib\hexo\index.js:232:12
    at tryCatcher (F:\Githexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Githexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\Githexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\Githexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\Githexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\Githexo\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\Githexo\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\Githexo\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\Githexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\Githexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\Githexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\Githexo\node_modules\bluebird\js\release\promise.js:638:18)
    at F:\Githexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at F:\Githexo\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
INFO  Start processing
INFO  Files loaded in 197 ms
INFO  Generated: 2017/05/11/hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2017/05/index.html
INFO  Generated: archives/2017/index.html
INFO  Generated: index.html
INFO  5 files generated in 169 ms
`
博主看一下是什么原因导致的主题更换不成功。

**Comment by GeekaholicLin** [comment]
有没有安装以下的依赖？
```  javascript
    npm install ejs --save
    npm install moment --save
    npm install utils-merge --save
```
还有你的Hexo版本是不是3.x？

**Comment by GeekaholicLin** [comment]
好像是ejs的版本问题，你先卸载ejs，再安装特定版本的ejs

``` javascript
    npm uninstall ejs --save
    npm install ejs@^1.0.0 --save
```

**Comment by yeechongyeung** [comment]
对，确实是ejs版本的问题，改为1.0.0版本后就编译通过了。

**Comment by GeekaholicLin** [comment]
既然解决了，那我关闭了哈~
